steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/avid-equator-417422/gs", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/avid-equator-417422/gs"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "package-calculator",
        "--image",
        "gcr.io/avid-equator-417422/gs",
        "--platform",
        "managed",
        "--region",
        "REGION",
      ]
